apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-public-catalog 
  annotations:
    github.com/project-slug: backstage-public-catalog 
spec:
  type: other
  lifecycle: unknown
